---
version: '2.1'
services:
  webtop:
    container_name: webtop
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/Toronto
    image: docker.io/adeelx/webtop-google-chrome:latest
    ports:
    - 3000:3000
    restart: unless-stopped
    shm_size: 1gb
    volumes:
    - ./config:/config
    - /var/run/docker.sock:/var/run/docker.sock
    cap_add:
    - SYS_ADMIN
